global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "coupon-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docekr.internal:8080']
  - job_name: "coupon-consumer"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docekr.internal:8080']